//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "generation_logs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product: String,
    pub input_type: String,
    #[sea_orm(column_type = "Text")]
    pub ui_intent: String,
    pub template_version: i32,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub artifacts: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub warnings: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub generation_time_ms: Option<i32>,
    pub user_id: i32,
    #[sea_orm(unique)]
    pub job_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_payload: Option<String>,
    pub queued_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub priority: i32,
    /// LLM model name used for generation (internal audit only)
    pub model_name: Option<String>,
    /// LLM provider used for generation (internal audit only)
    pub provider: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
