//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "llm_configs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub provider: String,
    pub endpoint_url: Option<String>,
    pub model_name: String,
    pub api_key: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub temperature: Option<f32>,
    pub max_tokens: Option<i32>,
    pub is_active: Option<bool>,
    /// Path to GGUF model file (for local-llama-cpp provider)
    pub model_path: Option<String>,
    /// Context window size (for local-llama-cpp provider)
    pub n_ctx: Option<i32>,
    /// Number of CPU threads (for local-llama-cpp provider)
    pub n_threads: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
