//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod company_rules;
pub mod generation_logs;
pub mod knowledge_bases;
pub mod llm_configs;
pub mod prompt_templates;
pub mod users;
