//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::company_rules::Entity as CompanyRules;
pub use super::generation_logs::Entity as GenerationLogs;
pub use super::knowledge_bases::Entity as KnowledgeBases;
pub use super::llm_configs::Entity as LlmConfigs;
pub use super::prompt_templates::Entity as PromptTemplates;
pub use super::users::Entity as Users;
